Format fix

diff --git a/tools/ots_remote_instance_start b/tools/ots_remote_instance_start
--- a/tools/ots_remote_instance_start
+++ b/tools/ots_remote_instance_start
@@ -27,10 +27,10 @@ out "${Green}=========================== ots REMOTE INSTANCE on {${THIS_HOST}} =
 
 # Have to CD because setup_ots.sh isn't safe to run in other directories than the ots root, die if it didn't work
 if [ "x$1" != "x" ]; then
-    setup_dir=$1
-    shift
+	setup_dir=$1
+	shift
 else
-    setup_dir=${SCRIPT_DIR}/../../../
+	setup_dir=${SCRIPT_DIR}/../../../
 fi
 info "Expected setup path     = ${setup_dir}/setup_ots.sh"
 cd $setup_dir || die "Couldn't chdir to ots setup directory on ${THIS_HOST}"
@@ -61,11 +61,11 @@ if [ "x$OTS_SETUP_TYPE" != "x" ]; then
   ENV_CACHE_FILE="${setup_dir}/.rte_${ENV_SUBSYSTEM}_setup_ots.sh"
 
   if [ -f $ENV_CACHE_FILE ]; then
-    info "Source remote env cache for ${EBold}${OTS_SETUP_TYPE}${DBold} on ${EBold}${THIS_HOST}${DBold}..."
-    source $ENV_CACHE_FILE
+	info "Source remote env cache for ${EBold}${OTS_SETUP_TYPE}${DBold} on ${EBold}${THIS_HOST}${DBold}..."
+	source $ENV_CACHE_FILE
   else
-    info "Sourcing remote setup_ots.sh, and hiding output, for ${EBold}${OTS_SETUP_TYPE}${DBold} on ${EBold}${THIS_HOST}${DBold}..."
-    source ./setup_ots.sh ${OTS_SETUP_TYPE} > /dev/null </dev/null  || die "Couldn't setup ots for ${OTS_SETUP_TYPE} on ${THIS_HOST}"
+	info "Sourcing remote setup_ots.sh, and hiding output, for ${EBold}${OTS_SETUP_TYPE}${DBold} on ${EBold}${THIS_HOST}${DBold}..."
+	source ./setup_ots.sh ${OTS_SETUP_TYPE} > /dev/null </dev/null  || die "Couldn't setup ots for ${OTS_SETUP_TYPE} on ${THIS_HOST}"
   fi
   info "Launching ots ${OTS_MODE}-mode for ${EBold}${OTS_SETUP_TYPE}${DBold} on ${EBold}${THIS_HOST}${DBold}..."
 
@@ -74,7 +74,7 @@ else # no setup type
   info "Sourcing remote setup_ots.sh, and hiding output, on ${EBold}${THIS_HOST}${DBold}..."
   source ./setup_ots.sh > /dev/null </dev/null  || die "Couldn't setup ots on ${THIS_HOST}"
   info "Launching ots ${OTS_MODE}-mode on ${EBold}${THIS_HOST}${DBold}..."
-  
+
 fi
 
 
